name: movplus_mvvm
description: A new Flutter project.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  flutter_hooks: ^0.18.3
  hooks_riverpod: ^1.0.3
  auto_route: ^4.0.1
  dio: ^4.0.6
  freezed_annotation: ^2.0.3
  json_annotation: ^4.5.0
  retrofit: '>=3.0.0 <4.0.0'
  iconly: ^1.0.1
  flutter_svg: ^1.0.3
  ua_client_hints: ^1.1.1
  youtube_player_flutter: ^8.0.0
  url_launcher: ^6.1.3
  
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^1.0.0
  auto_route_generator: any
  build_runner: 
  freezed: ^2.0.3+1
  json_serializable: ^6.2.0
  retrofit_generator: '>=4.0.0 <5.0.0'
  flutter_gen_runner:


flutter_gen:
  integrations:
    flutter_svg: true

flutter:

  
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/pngs/
    - assets/svgs/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
